trigger:
- main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  packageVersion: '1.0.0'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Default
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '/p:Version=$(packageVersion)'
    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: NuGetCommand@2
      displayName: 'NuGet pack'
      inputs:
        command: pack
        packagesToPack: '**/StringUtilities.csproj'
        versioningScheme: byEnvVar
        versionEnvVar: packageVersion
    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        publishVstsFeed: '$(System.TeamProject)/StringUtilities'
        allowPackageConflicts: true

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    pool:
      name: Default
    environment: production    
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deployment stage"
